export const FETCH_MESSEGES = 'FETCH_MESSEGES';
export const FETCH_MESSEGE_BY_ID_SUCCESS = 'FETCH_MESSEGE_BY_ID_SUCCESS';
export const FETCH_MESSEGE_BY_ID_INIT = 'FETCH_MESSEGE_BY_ID_INIT';
export const FETCH_MESSEGES_SUCCESS = 'FETCH_MESSEGES_SUCCESS';

export const FETCH_MESSEGES_INIT = 'FETCH_MESSEGES_INIT';
export const FETCH_MESSEGES_FAIL = 'FETCH_MESSEGES_FAIL';

export const UPDATE_MESSEGE_SUCCESS = 'UPDATE_MESSEGE_SUCCESS';
export const UPDATE_MESSEGE_FAIL = 'UPDATE_MESSEGE_FAIL';
export const RESET_MESSEGE_ERRORS = 'RESET_MESSEGE_ERRORS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
